#!/usr/bin/python2.7

GATE_DEPTH = -1.5
QUALIFY_DEPTH = -2
PATH_DEPTH = -1.5

MARK = 2

AUV_L_SPEED = 1
AUV_M_SPEED = 1.5
AUV_H_SPEED = 2
AUV_TURN_SPEED = 0.20

VISION_GATE_ERROR = 0.3
vision_qualifying_gate_ERROR = 0.3
VISION_PATH_ERROR = 0.5
VISION_ROULETTE_ERROR = 0.3
VISION_MARKER_ERROR = 0.4
VISION_DICE_ERROR = 0.4
